### ISSUE TITLE
Add Read SPI Flash Unique ID function.

### ISSUE THREAD

**Issue by sblpp** [Kuraga13/esptool_qt#2]
Hi , 
Can you  add Read SPI Flash Unique ID function ? thanks.
Maybe this Command is : 0x4B.

**Comment by Evgeny-SPB** [comment]
![ReadUniqueId](https://github.com/user-attachments/assets/124ea417-8126-4111-bb64-7505f237c8c8)

This Function is Experimental and works only on some chips. We recommend using ESP-IDF [SPI Flash API](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/spi_flash/index.html).
